- .gitignore
- Makefile
- lib/importer/index.js
- lib/importer/package-lock.json
- lib/importer/package.json
Using `make prototype NAME=something` will create a new prototype in prototypes/ and tell you what the next steps are. In addition to creating the prototype, it imports the local 'importer' package (eventual name TBD) so that any exported functions can be used in the prototype kit.  The 'importer' dependency will be reloaded by the prototype kit if any changes are made to it.
> Add helper script to setup new prototypes

- Makefile
When creating a prototype, we reference the local importer and as a result it will use its own local node_modules, if it is not up to date then this will introduce problems in the prototype.
Now we do an `npm i` in lib/importer to make sure its dependencies are up to date.
Fixes #8
> Ensure lib importer dependencies are installed for new prototype

- lib/importer/govuk-prototype-kit.config.json
- lib/importer/nunjucks/importer/macros/field_mapper.njk
- lib/importer/nunjucks/importer/macros/sheet_selector.njk
- lib/importer/nunjucks/importer/macros/table_view.njk
- lib/importer/templates/mapping.html
- lib/importer/templates/review.html
- lib/importer/templates/select_sheet.html
- prototypes/basic/app/views/mapping.html
- prototypes/basic/app/views/review.html
- prototypes/basic/app/views/select_sheet.html
Each template in the importer lib has a section that displays data, and to increase flexibility, we have wrapped those elements in nunjucks macros so that designers have more control over what they show and where.  Although they can just take the templates whole, this will also make it possible for them to make library calls and present that data to the macros directly.
> Wrap key functionality in nunjucks macros

- lib/importer/govuk-prototype-kit.config.json
- lib/importer/nunjucks/importer/macros/table_assets.njk
- lib/importer/package-lock.json
- lib/importer/templates/review.html
- prototypes/basic/app/routes.js
- prototypes/basic/app/views/review.html
- prototypes/basic/package-lock.json
- prototypes/basic/package.json
When using a scoped package (@register-dynamics/importer) the path to load the assets is no longer plugin-assets/importer but now includes the scoped package name.
To resolve this we have introduced a new macro for loading the table assets directly, without the user needing to know what they are.  This might be prettier if we had an obvious way to get the name of the package the code lives in.  We might in future load the package.json and read/encode and use it.
> Macro for table assets

- lib/importer/assets/js/selectable_table.js
- lib/importer/nunjucks/importer/macros/table_view.njk
Currently when the focus is removed from the table, the current visual selection is also removed. Whilst we will have taken what we want from the table at this point (the cell range) it may confuse users to see the selection disappear as they click a nearby submit button.
To configure this behaviour (remember the selection) the table should contain a data attribute called persist-selection like 
```
<table class="selectable" data-persist-selection="true">
```
Any other value, or the absence of the attribute will result in the old behavious of the selection being removed when the table focus is lost.
Resolves #27
> Do not remove visual selection when focus is lost

- doc/Makefile
- doc/README.md
- doc/init.js.patch
- doc/kit.js.patch
This was because of some path resolution issues. These have been manually patched for the files in the static site blob.
> Fix non-functional GOV.UK Frontend JS on static site

- lib/importer/backend.js
- lib/importer/sheets.js
Also obtains warning/error data from the backend and makes it available to the frontend macros, although nothing is currently done with it.
> Fix #38 - Ignore blank rows (but report a warning).

- lib/importer/backend.js
- lib/importer/backend.test.js
- lib/importer/index.js
- Don't ask for one more column than we have
-  While we're at it, refactor the sample padding code to try and find the bug that wasn't there, write a test to prove it wasn't there, and notice that the xlsx library uses `undefined` for missing values so we should too (instead of `null`)
> Dont pad too much

- lib/importer/backend.js
- lib/importer/backend.test.js
- lib/importer/package-lock.json
- lib/importer/package.json
This bypasses the `node-xlsx` library and just uses the underlying sheet.js library, so we can get access to extra metadata.
- This also means that we have access to the 'formatted string' version of a cell, so use that in the preview, which is nice for dates
- But mainly it should change nothing else in the frontend, and provides a basis for us to handle merged cells and access style information in future PRs
Resolves #35.
> Bypass Node XLSX

- lib/importer/backend.js
- lib/importer/backend.test.js
- lib/importer/index.js
- lib/importer/nunjucks/importer/macros/field_mapper.njk
- lib/importer/sheets.js
Shows a sample of the possible values for each column when mapping from columns to fields.
Optionally allows a limited number of sample items to be shown, and also to truncate each value so that the samples don't show extremely long strings across multiple lines.
In this screenshot the caption is optional and configurable (defaults to ''), and the text used for each table heading is also configurable in the macro using ...
```js
importerFieldMapper(
data, 
caption='', 
columnTitle='Column', 
examplesTitle='Example values', 
fieldsTitle='Fields'
)
```
> Show sample column values when mapping fields

- lib/importer/index.js
- lib/importer/nunjucks/importer/macros/sheet_selector.njk
- lib/importer/nunjucks/importer/macros/table_view.njk
- lib/importer/sheets.js
- lib/importer/templates/review.html
- lib/importer/templates/select_sheet.html
- prototypes/basic/app/views/mapping.html
- prototypes/basic/app/views/review.html
- prototypes/basic/app/views/select_sheet.html
On the sheet selection page, shows a preview of each sheet as the radio button is pressed, allowing users to check that it is the sheet that they want, which will be useful given the prevalence of both empty sheets and metadata sheets.
One issue we will need to work around is sheets with too many columns, currently we are using overflow-x to show a scrollbar but we might want to find a better way (such as limiting the number of columns etc).
It also removes the table view from the review screen as we now need to explicitly provide data rather than looking it up in the session.
> Show preview of imported sheet when selecting a sheet

- lib/importer/index.js
If we select from right to left, then the selection is invalid when used later on.  To avoid this we normalise it to ensure that the top left elements are less than or equal to the bottom right elements.
Resolves #49 
TODO: When we work on the footer selection we will abstract this code out as it will be re-used there.
> Normalise the header selection

- lib/importer/assets/css/selectable_table.css
- lib/importer/assets/css/sheet_selector.css
- lib/importer/assets/js/sheet_selector.js
- lib/importer/govuk-prototype-kit.config.json
- lib/importer/nunjucks/importer/macros/sheet_selector.njk
- lib/importer/nunjucks/importer/macros/table_view.njk
- Use a `<caption>` element which more accurately describes the table content for screen readers
- Use CSS `visibility` instead of `display` to control which sheet is shown which means invisible sheets continue to occupy screen space, so the below elements don't move around on the screen when the selection is changed, which is difficult for people with certain cognitive issues
- Use `aria-hidden` attributes to hide invisible sheets from screen readers
- Move CSS/JS into separate files for easier reuse in the docs
WDYT @rossjones ?
> Accessibility improvements to sheet selector component

- lib/importer/sheets.js
> Use backend.SessionSuggestDataRange rather than computing our own ranges

- lib/importer/backend.test.js
This caused an intermittent failure, when the random selection happened to fall a certain way.
> Typo in the tests!

- lib/importer/sheets.js
Previously, we were selecting rows based on the currently selected range, which was OK when the default initial header range was selected, but problematic when the user had already selected a header range.
Resolves #44.
> Fix #44: Always present the (at most) top 10 rows of the sheet in range selection

- lib/importer/backend.js
- lib/importer/govuk-prototype-kit.config.json
- lib/importer/index.js
- lib/importer/nunjucks/importer/macros/footer_selector.njk
- lib/importer/nunjucks/importer/macros/header_selector.njk
- lib/importer/nunjucks/importer/macros/range_selector.njk
- lib/importer/session.js
- lib/importer/sheets.js
- lib/importer/templates/mapping.html
- lib/importer/templates/review.html
- lib/importer/templates/select_footer_row.html
- lib/importer/templates/select_header_row.html
- lib/importer/templates/select_sheet.html
- lib/importer/templates/success.html
- lib/importer/templates/upload.html
- prototypes/basic/app/views/mapping.html
- prototypes/basic/app/views/review.html
- prototypes/basic/app/views/select_footer_row.html
- prototypes/basic/app/views/select_header_row.html
- prototypes/basic/app/views/select_sheet.html
- prototypes/basic/app/views/success.html
- prototypes/basic/app/views/upload.html
Adds an optional step after header selection for selecting any footer cells in the current sheet.  To do this the PR contains a refactor of the range selector so that users should now use `importerHeaderSelector` or `importerFooterSelector` rather than the lower-level `importerRangeSelector`; this allows us to fetch specific rows for each selector type in the outer macro, passing the rows to the inner importerRangeSelector macro.
The new footer selection step allows for no selection, either by pressing the Skip button or by not selecting any cells in the presented table.
> Add a footer selection step

- lib/importer/assets/docs/start.html
We found during testing that trying to explain to users how to get to the internal docs didn't really work. Instead lets try a link that only works if the PK is running.
> Add a link from static docs to plugin docs

- lib/importer/assets/docs/start.html
- lib/importer/package.json
- lib/importer/scripts/install-router.js
- prototypes/basic/app/routes.js
Here we use a postinstall hook to automatically add the required router lines to the app/routes.js, if it exists. We check first that this looks like a Prototype Kit prototype and not some other app.
Unfortunately we can't automatically reverse this process because npm doesn't run the pre/postuninstall hooks of dependent packages, because it sucks.
> Automatically install the plugin router

- .github/workflows/playwright.yml
- prototypes/basic/.gitignore
- prototypes/basic/README.md
- prototypes/basic/package-lock.json
- prototypes/basic/package.json
- prototypes/basic/playwright.config.js
- prototypes/basic/tests/helpers/fixtures.js
- prototypes/basic/tests/helpers/footer_selector_page.js
- prototypes/basic/tests/helpers/header_selector_page.js
- prototypes/basic/tests/helpers/mapping_page.js
- prototypes/basic/tests/helpers/sheet_selector_page.js
- prototypes/basic/tests/helpers/upload_page.js
- prototypes/basic/tests/simple.spec.js
- prototypes/basic/tests/tribbles.spec.js
Adds playwright to the basic prototype so that we can test the prototype where components are built and tested.  Currently only tests the happy path using tribbles.xlsx, but provides the foundation for further testing.  Does not yet test new prototype creation, this will be done as a separate PR
> Add playwright for running UI tests

- lib/importer/assets/css/selectable_table.css
- lib/importer/nunjucks/importer/macros/range_selector.njk
- lib/importer/nunjucks/importer/macros/table_view.njk
It was implemented in a style attribute, but would be better places in the selectable table's CSS
> Move caption styling to selectable css

- prototypes/basic/package-lock.json
- prototypes/basic/package.json
Currently the terminal is annoyingly noisy with warnings about sass, and this will override the govuk-pk version with a newer one
> Override sass version to remove terminal noise

- lib/importer/assets/js/selectable_table.js
If we use ctrl with the click when selecting multiple cells, it shows the context menu. Instead, we use the Command key (meta) when we have detected we're on a mac.
> When ctrl-clicking to select multiple cells, use cmd on mac

- Makefile
- prototypes/basic/package-lock.json
To make it easier to update dependencies when dependabot submits a new update, this adds a new target `update-deps` which will update the importer and the development prototype.
To make this work, had to restructure the `prototype` target so that it doesn't complain for other targets when `NAME=` is missing.
> Update makefile to simplify updates

- lib/importer/package-lock.json
- lib/importer/package.json
- lib/importer/src/config.test.js
- prototypes/basic/package-lock.json
When updating the configuration object, we want to make sure changes are persisted to disk so this commit adds tests to check that functionality does what is expected.
> Add tests to check config modifications are persisted.

- lib/importer/src/index.js
- prototypes/basic/app/assets/sass/application.scss
- prototypes/basic/app/config.json
- prototypes/basic/app/filters.js
- prototypes/basic/app/views/index.html
- prototypes/basic/app/views/info.html
- prototypes/basic/app/views/layouts/main.html
- prototypes/basic/app/views/mapping.html
- prototypes/basic/app/views/review.html
- prototypes/basic/app/views/select_footer_row.html
- prototypes/basic/app/views/select_header_row.html
- prototypes/basic/app/views/select_sheet.html
- prototypes/basic/app/views/success.html
- prototypes/basic/app/views/upload.html
- prototypes/basic/tests/simple.spec.js
- prototypes/basic/tests/small-file.spec.js
- prototypes/basic/tests/tribbles.spec.js
Modified the test prototype to represent the process of a monthly pension return service where users can upload a spreadsheet of salary information for processing. 
It re-introduces the review page with some information (sum and average of the salaries provided) as a starting point for operations on the uploaded data.  A new info page is added which is linked on the newly updated start page.
> Update test/default prototype

- prototypes/basic/app/assets/sass/application.scss
- prototypes/basic/app/views/layouts/main.html
* Removes the crown image from the header
* Changes the font to not use Transport (the default for prototype kit)
* Adds a warning message to every page clarifying that it is demonstration site
Feedback on content/styling welcome.
> Remove branding and clarify status of the demo

- lib/importer/src/config.js
- lib/importer/src/config.test.js
- lib/importer/src/index.js
- lib/importer/views/layouts/main.html
- lib/importer/views/plugin_config.html
- lib/importer/views/plugin_config_add_field.html
- lib/importer/views/plugin_config_disabled.html
- prototypes/basic/app/assets/sass/application.scss
- prototypes/basic/app/config.json
- prototypes/basic/app/views/layouts/footer.html
These changes allow the plugin to manage its own configuration with a set of pages. These pages allow the user to add/delete fields to be mapped along with the settings of the upload page.  
We may decide to hide the upload path as an advanced option as most users will not need to change it, and those that do are likely able to do so in the app/config.json file.
The pages can be accessed via `http://127.0.0.1:3000/importer/config`
These changes are quite isolated and so shouldn't break anything in the any in-use code.
> Add pages to manage configuration

- lib/importer/assets/docs/start.html
- lib/importer/nunjucks/importer/macros/field_mapper.njk
- lib/importer/src/attribute-types.js
- lib/importer/src/config.js
- lib/importer/src/config.test.js
- lib/importer/src/index.js
- lib/importer/src/session.test.js
- lib/importer/src/sheets.js
- lib/importer/views/plugin_config.html
- lib/importer/views/plugin_config_add_field.html
- prototypes/basic/package-lock.json
- prototypes/basic/tests/tribbles.spec.js
Changes configuration so that instead of just having a field name, it now accepts a field type (string or number) and a boolean which suggests whether the field is required in the mapping or not.
The codebase still supports the old style configuration (fields are a list of names) but defaults to not-required and string fields.
The new configuration structure looks like 
```
[
{ name: "Fieldname", type: "string", required: false }
]
```
where type can currently be one of "string" or "number"
> Change the structure for mapping fields in config

- .github/workflows/publish.yml
- lib/importer/.npmrc
- lib/importer/package-lock.json
- lib/importer/package.json
When merging to main, publish the lib/importer as a package to https://www.npmjs.com/package/@register-dynamics/importer
This github action only runs when a github release is published, so this PR does not involve itself in updating the package version in package.json.   
If in future we decide to publish multiple packages from here we can add a task to check both package.json have been updated and keep the versions in sync.
> Publish package on push

- lib/importer/nunjucks/importer/macros/field_mapper.njk
If the name of a column in the user-submitted data matches the name of a configured field, we now automatically select the field in the column's mapping drop-down.
We only do this if the user previously hasn't submitted a mapping. This is so that any fields they left blank will continue to be blank and won't be overriden by the default if they come back to the mapping page to correct an error.
> Auto-populate field names in the mapper if they match

- README.md
- prototypes/basic/package-lock.json
Explains how to perform a new release of the package, from updating the version to performing a github release.
The change to the demo prototype's package-lock is explained in this PR at https://github.com/register-dynamics/data-import/compare/describe-release-process?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R52 - it is the result of not updating it in the last releasse.
> Document the current release process

- lib/importer/src/index.js
- lib/importer/src/usage.js
- lib/importer/src/usage.test.js
- lib/importer/views/plugin_config.html
Adds a new option to the configuration page, to allow users to opt-in to usage data collection, which looks like:
Not 100% sure of the wording, but the functionality works as advertised, adding a new option to the `usage-data-config.json` file. 
Note this does not actually collect any data at present, but simply prints the event name out to the console.
> Manage collection of usage data

- lib/importer/assets/js/selectable_table.js
- lib/importer/nunjucks/importer/macros/footer_selector.njk
- lib/importer/nunjucks/importer/macros/header_selector.njk
- lib/importer/nunjucks/importer/macros/range_selector.njk
- lib/importer/nunjucks/importer/macros/sheet_selector.njk
- lib/importer/nunjucks/importer/macros/table_view.njk
- lib/importer/src/backend.js
- lib/importer/src/functions.js
- lib/importer/src/index.js
- lib/importer/src/session.js
- lib/importer/src/session.test.js
- lib/importer/src/sheets.js
- lib/importer/src/sheets.test.js
Allows tables  to have a table header row (THEAD) that contains values from the following list:
* No headers
* Base26 representation of the column index 
* The selected header row from the source file 
* The target header titles from the domain object (target).
There are obvious contraints on their use (e.g. can't use target mode until mapping done, can't use source until a sheet is selected with a header range).
> Enable header row display in tables

- prototypes/basic/package-lock.json
- prototypes/basic/package.json
Updates playwright test and main dependencies together.  After merging anybody wanting to run the tests will have to run the following to get the necessary browsers installed.
```
npx playwright install
```
> Update playwright for testing

- lib/importer/src/dudk/backend.js
- lib/importer/src/dudk/backend.test.js
This adds SessionSuggestFields, a utility function in the backend that cross-references type guesses from SessionGuessTypes and a domain model's list of fields, to suggest possible fields (and corresponding formats) for each column.
It exists simply to save frontend logic containing logic to peruse data structures!
> #786: Suggest fields for columns

- lib/importer/package-lock.json
- lib/importer/package.json
- prototypes/basic/package-lock.json
- prototypes/basic/package.json
Updates the test packages, although it is necessary now to run an LTS version (if you want to run tests) of nodejs (an even version number).
> Bring test dependencies up to date

- prototypes/basic/app/config.json
- prototypes/basic/app/views/index.html
Makes 'Salary' a required field so that errors are viewable in the demonstration.  Adds some context to the homepage explaining that it is required.
> Explain that salary is required

- lib/importer/src/index.js
We use the session to hold error information to be displayed on the page.  We previously used a function that could be called which would remove any error artifacts from the session before the request was processed.  This was however not applied consistently.
This PR now introduces a middleware which will remove session data from the session at the start of each request.
> Clean up errors on each new request

- lib/importer/src/dudk/sheets.js
- lib/importer/src/dudk/sheets.test.js
- lib/importer/templates/review.html
The previous version of this function was incorrectly locating the cells with errors in based on the source headers (e.g. titles in sheet) instead of the mapping.  This meant that we were not identifying the errors in each row, unless the mapping was identical to the source headers.
This change ensures that the errors are shown and are grouped correctly along with local context (previous and following rows).
Updating of errors into include field name will be added in a separate PR
> Correctly map errors into presentation structure

- lib/importer/src/dudk/sheets.js
Currently during mapping we identify the data range to select some examples from, but the call that is made expects an inclusive range, and we want an exclusive one. Due to the lack of options wrt range types we instead just decrement the range we want to retrieve.
We may want to consider having different range types to avoid having to add/subtract one based on requirements, and perhaps make iteration and calculations easier
> Don't include footer row in example values during mapping

- lib/importer/src/config.js
- lib/importer/src/config.test.js
- lib/importer/src/index.js
- lib/importer/templates/upload.html
- lib/importer/views/plugin_config.html
- prototypes/basic/app/config.json
- prototypes/basic/app/views/upload.html
In some cases files are uploaded that contain only a single sheet.
It seems wasteful to show the user the single sheet and expect them to continue, so we will provide a config option that allows owners of the prototype to decide whether to always show the sheet selection screen, or to skip it when there is only one sheet.  
As the sheet selection may still be valuable as a visual indicator that the user has uploaded the correct sheet, we will allow the configutation options to be "manual" or "automatic" with 'manual' always showing the select sheet screen, and 'automatic' skipping it when it can.
The default, should the implementor never set a value, is manual to avoid an unexpected change of behaviour after updating the library.
Resolves #197
> Configuration for auto-sheet selection when only one

- lib/importer/assets/docs/start.html
Update the documentation to show how users can install the plugin using the usual npm process.
Of course, if your default registry has been modified you'll need to specify it, but if users are using custom registries the likelihood is that they know how to specify which to use on a case-by-case basis.
> Update install instructions in docs

- lib/importer/nunjucks/views/error-handling/server-error.njk
Template was missing the govukFooter include, and so was failing to show the server error when it happened.
> Fix server error page

- lib/importer/templates/review.html
- lib/importer/views/plugin_config.html
- prototypes/basic/app/views/review.html
Comments added to the review page in the demo (and the source template) explain how to use the errors returned from the backend.
In addition, the config page has a short paragraph in case the user thought they were edited there.  This points them back to the review template.
> Provide basic docs on error messages

- lib/importer/assets/js/selectable_table.js
- lib/importer/nunjucks/importer/macros/footer_selector.njk
- lib/importer/nunjucks/importer/macros/header_selector.njk
- lib/importer/nunjucks/importer/macros/table_view.njk
- lib/importer/src/functions.js
- lib/importer/templates/select_footer_row.html
- lib/importer/templates/select_header_row.html
- prototypes/basic/app/views/select_footer_row.html
- prototypes/basic/app/views/select_header_row.html
When selecting header and footer rows, they are stored in the current session for when the user gets to the mapping screen.  Unfortunately, if the user goes back to the header or footer selection screen, their previous selections are not shown even if they are still held in the backend state.
This PR includes the current header/footer selection in the appropriate hidden form elements that denote the previous selection. Because when showing footers the row index in the range is for the entire sheet, not just the n rows being shown, this was failing to highlight the footer rows (when present).  To resolve this, we added data-row-index to the rows in the table, allowing us to access the row directly.  Perhaps it might be worth adding data-cell-position to TDs or data-column-index to columns …
> Set current selection values on header/footer selection screens
